### ISSUE TITLE
The bar corresponding to the selected material should be in different color in the barChart

### ISSUE THREAD

**Issue by alikn** [alikn/project530#41]

**Comment by yasminf** [comment]
@alikn I have made the changes so that the bar for selected material is in a different color. However this has unveiled another problem, the bar chart only changes when as sectorChange event is triggered and therefore remains the same the even when the material changes. Is there any where to get highlighted sector (the one in red) based on the selected material ? I am open to suggestions if you have any other ideas on how to solve this.

**Comment by alikn** [comment]
I am not sure if I understand it correctly. In general, the state of all the elements in the page should be known once we know the material and the sector, both of which you can get from dataProcess class using getChosenMaterial and getChosenSector methods at anytime. If you want you can add a listener for the material or sector change as well directly. Let me know if I could be of any help.

**Comment by alikn** [comment]
@yasminf how are we doing on this issue?

**Comment by yasminf** [comment]
#fixed

**Comment by JasvirBhathal** [comment]
Reviewed
