### ISSUE TITLE
Use "bolder" colors for the bar chart

### ISSUE THREAD

**Issue by alikn** [alikn/project530#65]
Yasmin, I just saw Bruce's comment on the pdf he sent us which says the following about the bar graph: "I would reduce the width of the bars by about 30% and choose bolder colors. Shouln't all of the colors be different? Also, use notation large caps for PM, TPM, and VOC (e.g. PM2.5(with smaller font for 2.5, 10)).
We have implemented some already (caps for labels) and some are practically dependent on other things (bar width). 

Could you please make the yellow color of the bars a bit sharper?

![image](https://cloud.githubusercontent.com/assets/7191926/7110758/8699a89a-e16b-11e4-9aca-dd63e1129ed5.png)

**Comment by yasminf** [comment]
ok ali will change it once I am done working on the report. If I go with
brighter yellow though I am afraid it will be too similar to the yellow for
open sources which could be even more confusing given for PM2.5 most of the
lines are yellow. I could change it to red or alternatively to  dark grey
since we have more data on the map I dont think grey would have the
monotone effect it had before ... what do yout think?
